name: allsql
description: AllSQL is an open-source compact browser-based SQL Compiler, built using Flutter.

publish_to: 'none'

version: 1.3.0+4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi_web: ^0.4.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:

  uses-material-design: true
